In [1]:
import torch
import pandas

# introdduction to tensors

### Creating scalars



In [4]:
#scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [6]:
# vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
# matrix

matrix= torch.tensor([[7, 1], 
                     [5, 3]])

matrix

tensor([[7, 1],
        [5, 3]])

In [21]:
TENSOR= torch.tensor([[[[3, 5], 
                       [4, 6],
                       [1, 9]]]])

TENSOR

tensor([[[[3, 5],
          [4, 6],
          [1, 9]]]])

In [22]:
# To check the dimension of a tensor we use `torch.ndim`

print(f'The dimension of the variable "scalar" is {scalar.ndim}.\nThe dimension of the variable "vector" is {vector.ndim}.\nThe dimension of the variable "matrix" is {matrix.ndim}.\
\nThe dimension of the variable "TENSOR" is {TENSOR.ndim}.')

The dimension of the variable "scalar" is 0.
The dimension of the variable "vector" is 1.
The dimension of the variable "matrix" is 2.
The dimension of the variable "TENSOR" is 4.


In [23]:
# to check the shapes of the above

print(f'The shape of the variable "scalar" is {scalar.shape}.\nThe shape of the variable "vector" is {vector.shape}.\nThe shape of the variable "matrix" is {matrix.shape}.\
\nThe shape of the variable "TENSOR" is {TENSOR.shape}.')

The shape of the variable "scalar" is torch.Size([]).
The shape of the variable "vector" is torch.Size([2]).
The shape of the variable "matrix" is torch.Size([2, 2]).
The shape of the variable "TENSOR" is torch.Size([1, 1, 3, 2]).


<h3>Summary of types of tensor objects</h3>

| Name   | What is it?                                     | Number of Dimensions | Variable Nomenclature |
| ------: | -----------------------------------------------: | --------------------: | ---------------------: |
| Scaler | A single number, representing only magnitude     | 0                    | Lower (a)             |
| Vector | A number with direction, can have many other numbers | 1 | lower (y) |
| Matrix | A 2 dimensional array of numbers | 2 | Upper (Q) |
| Tensor | A n-dimensional array of numbers | Can be any number: 0 = scalar, 1 = vector, 2= matrix | Upper (X) |

### Torch object xtics

In [26]:
TENSOR= torch.tensor([[[1,4], [5, 6]], 
              [[2, 7], [3, 5]],
              [[7, 9], [2, 9]]])

In [29]:
TENSOR.shape

torch.Size([3, 2, 2])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.dtype

torch.int64

### Random Tensors

Why Random  Tensors?

this is because machine learning models usually start training with a large set of random numbers and keep adjusting weights at each epoch until it achieves its goal or completes the number of epochs

In [31]:
# Creating a `Random Tensors` of shape (3, 4)

r_tensor= torch.rand(3, 4)
r_tensor

tensor([[0.4779, 0.2687, 0.6532, 0.1329],
        [0.1303, 0.1637, 0.7457, 0.9641],
        [0.6145, 0.3679, 0.5671, 0.7304]])

In [34]:
# create a random tensor with similar shape to an image tensor. the shape of an image tensor is given as (height, width, channels)
# example a 255 pixels square color image will be (224, 224, 3) as there are 3 color channels for thr RGB

rand_image= torch.rand(224, 224, 3)
rand_image.shape, rand_image.ndim

(torch.Size([224, 224, 3]), 3)

### Tensors of Zeros and Ones



In [35]:
# Create a tensor of zeros
zero_tensor= torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
# create a tensor of ones

one_tensor= torch.ones(3, 4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

torch.range(start, end, step) the `end` is exclusive and the start is inclusive. however range is to be depreccated in future versions and thus a better fix will be torch.arange(start, end, step)

In [40]:
# create a torch range
one_to_ten= torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# To create a tensor like another, we use the rand, zero or ones_like the tensor we are trying to copy

torch.rand_like(one_tensor) # created a random tensor like one_tensor created above

tensor([[0.4325, 0.5556, 0.9302, 0.3229],
        [0.8370, 0.7735, 0.6428, 0.9074],
        [0.1423, 0.2514, 0.2625, 0.6721]])

### Tensor Datatypes

when creating a tensor there are 3 important parameters, are 

| Tensor parameter | Action | 
| :---------------- | :-------|
| dtype | defaults to `None`. Used to set the datatype for the objects created eg. torch.float32, torch.float64, torch.float16/torch.half, torch.bfloat16 : https://pytorch.org/docs/stable/tensor_attributes.html |
| device | default to `None`. This sets the device on which the tensor will be created. If utilizing a GPU using the passing the type argument set the device |
| requires_grad | defaults to `False`. This defines whether gradients should be tracked on operations with this tensor. |

In [53]:
# integers

float_32= torch.tensor([[1,2,3],
                        [4,5,6]],
                       dtype= torch.float32)
print(float_32, float_32.dtype, '\n')

# to change the data type of a tensor, we use the type method

float_16= float_32.type(torch.float16)
print(float_16)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32 

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


## Note
there are 3 main error we will run into with PyTorch and deep learning. These are:
<ol>
    <li>Tensor not right datatype</li>
    <li>Tensor not right shape</li>
    <li>Tensor not on right device</li>
</ol>