In [1]:
import torch
import pandas

# introdduction to tensors

### Creating scalars



In [2]:
#scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
# vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [4]:
# matrix

matrix= torch.tensor([[7, 1], 
                     [5, 3]])

matrix

tensor([[7, 1],
        [5, 3]])

In [5]:
TENSOR= torch.tensor([[[[3, 5], 
                       [4, 6],
                       [1, 9]]]])

TENSOR

tensor([[[[3, 5],
          [4, 6],
          [1, 9]]]])

In [6]:
# To check the dimension of a tensor we use `torch.ndim`

print(f'The dimension of the variable "scalar" is {scalar.ndim}.\nThe dimension of the variable "vector" is {vector.ndim}.\nThe dimension of the variable "matrix" is {matrix.ndim}.\
\nThe dimension of the variable "TENSOR" is {TENSOR.ndim}.')

The dimension of the variable "scalar" is 0.
The dimension of the variable "vector" is 1.
The dimension of the variable "matrix" is 2.
The dimension of the variable "TENSOR" is 4.


In [7]:
# to check the shapes of the above

print(f'The shape of the variable "scalar" is {scalar.shape}.\nThe shape of the variable "vector" is {vector.shape}.\nThe shape of the variable "matrix" is {matrix.shape}.\
\nThe shape of the variable "TENSOR" is {TENSOR.shape}.')

The shape of the variable "scalar" is torch.Size([]).
The shape of the variable "vector" is torch.Size([2]).
The shape of the variable "matrix" is torch.Size([2, 2]).
The shape of the variable "TENSOR" is torch.Size([1, 1, 3, 2]).


<h3>Summary of types of tensor objects</h3>

| Name   | What is it?                                     | Number of Dimensions | Variable Nomenclature |
| ------: | -----------------------------------------------: | --------------------: | ---------------------: |
| Scaler | A single number, representing only magnitude     | 0                    | Lower (a)             |
| Vector | A number with direction, can have many other numbers | 1 | lower (y) |
| Matrix | A 2 dimensional array of numbers | 2 | Upper (Q) |
| Tensor | A n-dimensional array of numbers | Can be any number: 0 = scalar, 1 = vector, 2= matrix | Upper (X) |

### Torch object xtics

In [8]:
TENSOR= torch.tensor([[[1,4], [5, 6]], 
              [[2, 7], [3, 5]],
              [[7, 9], [2, 9]]])

In [9]:
TENSOR.shape

torch.Size([3, 2, 2])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.dtype

torch.int64

### Random Tensors

Why Random  Tensors?

this is because machine learning models usually start training with a large set of random numbers and keep adjusting weights at each epoch until it achieves its goal or completes the number of epochs

In [12]:
# Creating a `Random Tensors` of shape (3, 4)

r_tensor= torch.rand(3, 4)
r_tensor

tensor([[0.8971, 0.7046, 0.8100, 0.3257],
        [0.1715, 0.0914, 0.7341, 0.8216],
        [0.9858, 0.0982, 0.1723, 0.8095]])

In [13]:
# create a random tensor with similar shape to an image tensor. the shape of an image tensor is given as (height, width, channels)
# example a 255 pixels square color image will be (224, 224, 3) as there are 3 color channels for thr RGB

rand_image= torch.rand(224, 224, 3)
rand_image.shape, rand_image.ndim

(torch.Size([224, 224, 3]), 3)

### Tensors of Zeros and Ones



In [14]:
# Create a tensor of zeros
zero_tensor= torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
# create a tensor of ones

one_tensor= torch.ones(3, 4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

torch.range(start, end, step) the `end` is exclusive and the start is inclusive. however range is to be depreccated in future versions and thus a better fix will be torch.arange(start, end, step)

In [16]:
# create a torch range
one_to_ten= torch.arange(1, 11, 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# To create a tensor like another, we use the rand, zero or ones_like the tensor we are trying to copy

torch.rand_like(one_tensor) # created a random tensor like one_tensor created above

tensor([[0.3592, 0.4422, 0.8915, 0.1732],
        [0.8425, 0.1850, 0.4756, 0.9808],
        [0.9310, 0.5241, 0.9084, 0.5102]])

### Tensor Datatypes

when creating a tensor there are 3 important parameters, are 

| Tensor parameter | Action | 
| :---------------- | :-------|
| dtype | defaults to `None`. Used to set the datatype for the objects created eg. torch.float32, torch.float64, torch.float16/torch.half, torch.bfloat16 : https://pytorch.org/docs/stable/tensor_attributes.html |
| device | default to `None`. This sets the device on which the tensor will be created. If utilizing a GPU using the passing the type argument set the device |
| requires_grad | defaults to `False`. This defines whether gradients should be tracked on operations with this tensor. |

In [18]:
# integers

float_32= torch.tensor([[1,2,3],
                        [4,5,6]],
                       dtype= torch.float32)
print(float_32, float_32.dtype, '\n')

# to change the data type of a tensor, we use the type method

float_16= float_32.type(torch.float16)
print(float_16)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32 

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


## Note
there are 3 main error we will run into with PyTorch and deep learning. These are:
<ol>
    <li>Tensor not right datatype</li>
    <li>Tensor not right shape</li>
    <li>Tensor not on right device</li>
</ol>

## Getting information from Tensors

In [25]:
# create a random tensor

tensor= torch.rand([3, 5])

In [26]:
# to check the shape of a tensor, we use tensor.shape or .size()

print(tensor.shape, '\n', tensor.size())

torch.Size([3, 5]) 
 torch.Size([3, 5])


In [29]:
# to chect the data type of a tensor we use the attribute of a tensor called dtype

tensor.dtype

torch.float32

In [30]:
# to check the device a tensor is on, we use the .device attributes

tensor.device

device(type='cpu')

## Manipulating Tensors

Tensor operation include:
1. additions
2. subtraction
3. multiplication (element-wise)
4. division
5. matrix multiplication

In [34]:
# addition

tensor_a= torch.tensor([1, 2, 3])

print(tensor_a + 10)

# subtraction

print(tensor_a - 10)

# multiplication

print(tensor_a * 10)

# division

print(tensor_a / 10)


tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


### matrix multiplication

there are 2 types of multiplication in torch

1. element-wise
2. Dot product multiplication (matrix multiplication shape (m, n) * (n, k) and the resulting matrix is the dimension of the outer matrix.

In [36]:
tensor= torch.tensor([1, 2, 3])

In [37]:
%%time

value= 0
for i in range(len(tensor)):
    value+= tensor[i] + tensor[i]

print(tensor)

tensor([1, 2, 3])
CPU times: user 1.95 ms, sys: 2.89 ms, total: 4.84 ms
Wall time: 4.28 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 873 µs, sys: 2.39 ms, total: 3.26 ms
Wall time: 3.83 ms


tensor(14)

In [40]:
tensor_a= torch.tensor([[3, 2], 
               [4, 5],
               [6, 7]])

tensor_b= torch.tensor([[1, 2],
                        [3, 4], 
                        [5, 6]])

In [47]:
torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
# to fix transpose issues, we use a transpose on one of the matrices
 
torch.matmul(tensor_a, tensor_b.T)

tensor([[ 7, 17, 27],
        [14, 32, 50],
        [20, 46, 72]])

### Finding min, max, mean, sum, etc (tensor aggregation)



In [53]:
# find the min
print(torch.min(torch.min(tensor_a)))

print(torch.max(tensor_a))

print(torch.mean(tensor_a.type(torch.float32))) #can only work on dtype <= torch.float32

print(torch.sum(tensor_a))

tensor(2)
tensor(7)
tensor(4.5000)
tensor(27)


In [55]:
# argmin and argmax, are methods used to get the index position of the max or min value in a tensor

tensor_a.argmax()

tensor(5)

In [56]:
tensor_a.max()

tensor(7)

In [57]:
tensor_a

tensor([[3, 2],
        [4, 5],
        [6, 7]])

## Reshaping, stacking, squeezing, and unsqueezing tensors

